name: Run Shell Script

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest  # You can change the OS to windows-latest or macos-latest based on your needs
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Shell Script
        run: |
          #chmod +x example_deployment.sh  # Make sure the script is executable
          ls -la
          ././bash/example_deployment.sh

      - name: print ip
        run: |
          ifconfig
          ping google.com

        
          



