name: Update README on .tf Changes

on:
  push:
    paths:
      - '**/*.tf'  # Triggers on any changes to .tf files

jobs:
  update-readme:
    runs-on: ubuntu-latest  # This specifies the environment to run the job

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Ensures that the workflow fetches just the latest commit

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.3.5'  # Specify your Terraform version here

      - name: Extract information from .tf files
        id: extract_info
        run: |
          # Here you can extract information from .tf files.
          # For now, let's just get the names of the .tf files modified.
          
          echo "Extracting relevant info from .tf files"
          
          # Example: We will extract all the .tf filenames that were changed
          TF_FILES=$(git diff --name-only $GITHUB_SHA $GITHUB_SHA^ | grep '\.tf$')

          # Save that list to a variable for use in the next steps
          echo "Changed TF files: $TF_FILES"
          
          # Save the result in an environment variable to pass to the next step
          echo "TF_FILES=$TF_FILES" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          echo "Updating README.md with new information"
          
          # Here we will append the list of changed .tf files to the README.md
          echo -e "\n## Terraform Files Changed\n$TF_FILES" >> README.md

      - name: Commit changes to README.md
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m 'Update README with changed Terraform files'
          git push
